souffle: souffle::ast::SipsMetric Class Reference
souffle::ast::SipsMetric Class Reference abstract
Class for SIPS cost-metric functions Each subclass represents a different heuristic used for evaluating the cost of choosing an atom next in the schedule.
#include <SipsMetric.h>
Public Member Functions
std::vector< unsigned int > getReordering (const Clause *clause) const
Determines the new ordering of a clause after the SIPS is applied.
virtual ~SipsMetric ()=default
Static Public Member Functions
static std::unique_ptr< SipsMetric > create (const std::string &heuristic, const TranslationUnit &tu)
Create a SIPS metric based on a given heuristic.
Protected Member Functions
virtual std::vector< double > evaluateCosts (const std::vector< Atom *> atoms, const BindingStore &bindingStore) const =0
Evaluates the cost of choosing each atom next in the current schedule.
Detailed Description
Class for SIPS cost-metric functions Each subclass represents a different heuristic used for evaluating the cost of choosing an atom next in the schedule.
Definition at line 39 of file SipsMetric.h.
Constructor & Destructor Documentation
~SipsMetric()
virtual souffle::ast::SipsMetric::~SipsMetric () virtual default
Member Function Documentation
create()
std::unique_ptr< SipsMetric > souffle::ast::SipsMetric::create (const std::string & heuristic, const TranslationUnit & tu) static
Create a SIPS metric based on a given heuristic.
Definition at line 62 of file SipsMetric.cpp.
References souffle::ast::TranslationUnit::getAnalysis().
Referenced by souffle::ast::transform::ReorderLiteralsTransformer::transform(), and souffle::AstToRamTranslator::translateProgram().
{
     if (heuristic == "strict")
         return std::make_unique<StrictSips>();
     else if (heuristic == "all-bound")
         return std::make_unique<AllBoundSips>();
     else if (heuristic == "naive")
         return std::make_unique<NaiveSips>();
     else if (heuristic == "max-bound")
         return std::make_unique<MaxBoundSips>();
     else if (heuristic == "max-ratio")
         return std::make_unique<MaxRatioSips>();
     else if (heuristic == "least-free")
         return std::make_unique<LeastFreeSips>();
     else if (heuristic == "least-free-vars")
         return std::make_unique<LeastFreeVarsSips>();
     else if (heuristic == "profile-use")
         return std::make_unique<ProfileUseSips>(*tu.getAnalysis<analysis::ProfileUseAnalysis>());
     else if (heuristic == "delta")
         return std::make_unique<DeltaSips>();
     else if (heuristic == "input")
         return std::make_unique<InputSips>(*tu.getAnalysis<analysis::RelationDetailCacheAnalysis>(),
                 *tu.getAnalysis<analysis::IOTypeAnalysis>());
     else if (heuristic == "delta-input")
         return std::make_unique<DeltaInputSips>(*tu.getAnalysis<analysis::RelationDetailCacheAnalysis>(),
                 *tu.getAnalysis<analysis::IOTypeAnalysis>());
     // default is all-bound
     return create("all-bound", tu);
 }
evaluateCosts()
virtual std::vector<double> souffle::ast::SipsMetric::evaluateCosts (const std::vector< Atom *> atoms, const BindingStore & bindingStore) const protected pure virtual
Evaluates the cost of choosing each atom next in the current schedule.
Parameters
atoms atoms to choose from; may be nullptr
bindingStore the variables already bound to a value
Implemented in souffle::ast::DeltaInputSips, souffle::ast::InputSips, souffle::ast::DeltaSips, souffle::ast::ProfileUseSips, souffle::ast::LeastFreeVarsSips, souffle::ast::LeastFreeSips, souffle::ast::MaxRatioSips, souffle::ast::MaxBoundSips, souffle::ast::NaiveSips, souffle::ast::AllBoundSips, and souffle::ast::StrictSips.
Referenced by getReordering().
getReordering()
std::vector< unsigned int > souffle::ast::SipsMetric::getReordering (const Clause * clause) const
Determines the new ordering of a clause after the SIPS is applied.
Parameters
clause clause to reorder
Returns
the vector of new positions; v[i] = j iff atom j moves to pos i
Definition at line 33 of file SipsMetric.cpp.
References souffle::ast::BindingStore::bindVariableStrongly(), and evaluateCosts().
Referenced by souffle::ast::transform::ReorderLiteralsTransformer::reorderClauseWithSips().
{
     BindingStore bindingStore(clause);
     auto atoms = getBodyLiterals<Atom>(*clause);
     std::vector<unsigned int> newOrder(atoms.size());
     size_t numAdded = 0;
     while (numAdded < atoms.size()) {
         // grab the index of the next atom, based on the SIPS function
         const auto& costs = evaluateCosts(atoms, bindingStore);
         auto minIdx = std::distance(costs.begin(), std::min_element(costs.begin(), costs.end()));
         const auto* nextAtom = atoms[minIdx];
         assert(nextAtom != nullptr && "nullptr atoms should have maximal cost");
         // set all arguments that are variables as bound
         for (const auto* arg : nextAtom->getArguments()) {
             if (const auto* var = dynamic_cast<const Variable*>(arg)) {
                 bindingStore.bindVariableStrongly(var->getName());
             }
         }
         newOrder[numAdded] = minIdx;  // add to the ordering
         atoms[minIdx] = nullptr;      // mark as done
         numAdded++;                   // move on
     }
     return newOrder;
 }
The documentation for this class was generated from the following files:
ast/utility/SipsMetric.h
ast/utility/SipsMetric.cpp